### ISSUE TITLE
Incorrect width with certain unicode characters

### ISSUE THREAD

**Issue by rmcgibbo** [guigui64/stybulate#14]
**Describe the bug**
It looks like there's an incorrect width calculation when rows contain a "✔" character (https://www.compart.com/en/unicode/U+2714). This seems related to issue #9 and issue #1.

**To Reproduce**
Here's a test case.
```
use stybulate::{Table, Style, Cell, Headers};

fn main() {
    let table = Table::new(Style::FancyGithub, vec![vec![
        Cell::from("✔"),
        Cell::from("foo"),
    ]], Some(Headers::from(vec!["Hello", "World"]))).tabulate();
    println!("{}", table);
}
```

Produces this result, (Linux, gnome terminal):

![image](https://user-images.githubusercontent.com/641278/124607410-d1d89180-de3b-11eb-9c4a-6f059ebeb856.png)

**Expected behavior**
The vertical lines should be aligned between the header and the first row, rather than slightly offset.

**Toolchain**
 - rustc 1.52.1, stybulate 1.1.1

**Comment by guigui64** [comment]
Hello, it is unfortunately no longer possible for me to maintain this library. If by any chance you want to maintain it or know someone that would like to do it, please let me know!

**Comment by rmcgibbo** [comment]
Understood.
